player = turtle.clone()
fat.zombe = turtle.clone()
fast.zombe = turtle.clone()
shooting = turtle.clone()
turtle.register_shape("trash.gif")
turtle.register_shape("trash.gif")
turtle.register_shape("trash.gif")
food = turtle.clone()
food.shape("trash.gif")